fixes #671: only published dataset and its published properties should be accessible
getodk/central-backend pull request #689
Opened 2022-11-17 21:58 UTC by sadiqkhoja

Closes #671

#### What has been done to verify that this works as intended?
Added integration tests

#### Why is this the best possible solution? Were any other approaches considered?
none

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
APIs should now return only published datasets with its published properties. 
On the frontend we have to update download dataset link and test that linking dataset to attachment is working - especially it links only published datasets

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.
We should mention that dataset related APIs only returns published datasets, explicitly mention what do we mean by "published datasets" and "published property"

#### Before submitting this PR, please make sure you have:

- [ ] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [ ] verified that any code from external sources are properly credited in comments

2022-11-17 22:07 UTC, sadiqkhoja commented on lib/model/query/datasets.js
>  const getByName = (datasetName, projectId) => ({ all }) =>
`Datasets.getByName` is called from a single place and it expects to receive only published dataset with its published properties

2022-11-17 22:08 UTC, sadiqkhoja commented on lib/model/query/datasets.js
> +const getByProjectAndName = (projectId, name, excludeUnpublished = false) => ({ maybeOne }) => maybeOne(sql`
if `excludeUnpublished` is true then we only return published properties

2022-11-17 22:10 UTC, sadiqkhoja commented on lib/resources/datasets.js
> +  service.get('/projects/:projectId/datasets/:name.csv', endpoint(({ Datasets, Entities, Projects }, { params, auth }, _, response) =>
I like the `:name.csv` endpoint, it works with integration tests that we have, do you see any problem if dataset name is strange? I can definitely change this to `entities.csv`

2022-11-18 17:30 UTC, ktuite approved these changes

2022-11-18 17:34 UTC, sadiqkhoja commented on test/integration/api/datasets.js
> -    describe('projects/:id/datasets/:dataset/download GET', () => {
add a test for checking unpublished dataset can't be linked to a form attachment

2022-11-18 18:44 UTC, lognaturel requested changes
See https://github.com/getodk/central-backend/pull/656#discussion_r1026761828 for one more revision to the dataset download endpoint!

2022-11-21 19:06 UTC, lognaturel approved these changes

2022-11-21 19:08 UTC, merged